package cn.mbg.mapper;

import cn.mbg.beans.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_users
     *
     * @mbggenerated Fri Jun 21 23:14:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_users
     *
     * @mbggenerated Fri Jun 21 23:14:25 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_users
     *
     * @mbggenerated Fri Jun 21 23:14:25 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_users
     *
     * @mbggenerated Fri Jun 21 23:14:25 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_users
     *
     * @mbggenerated Fri Jun 21 23:14:25 CST 2019
     */
    int updateByPrimaryKey(User record);
}