package com.xueyuan.beans;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.title
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.price
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.author
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.img_path
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.order_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.bcount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Integer bcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_order_details.amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Double amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.id
     *
     * @return the value of bs_order_details.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.id
     *
     * @param id the value for bs_order_details.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.title
     *
     * @return the value of bs_order_details.title
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.title
     *
     * @param title the value for bs_order_details.title
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.price
     *
     * @return the value of bs_order_details.price
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.price
     *
     * @param price the value for bs_order_details.price
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.author
     *
     * @return the value of bs_order_details.author
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.author
     *
     * @param author the value for bs_order_details.author
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.img_path
     *
     * @return the value of bs_order_details.img_path
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.img_path
     *
     * @param imgPath the value for bs_order_details.img_path
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.order_id
     *
     * @return the value of bs_order_details.order_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.order_id
     *
     * @param orderId the value for bs_order_details.order_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.bcount
     *
     * @return the value of bs_order_details.bcount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Integer getBcount() {
        return bcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.bcount
     *
     * @param bcount the value for bs_order_details.bcount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setBcount(Integer bcount) {
        this.bcount = bcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_order_details.amount
     *
     * @return the value of bs_order_details.amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_order_details.amount
     *
     * @param amount the value for bs_order_details.amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }
}