package com.xueyuan.beans;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.create_date
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.state
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.user_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.total_count
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_orders.total_amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    private Double totalAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.id
     *
     * @return the value of bs_orders.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.id
     *
     * @param id the value for bs_orders.id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.create_date
     *
     * @return the value of bs_orders.create_date
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.create_date
     *
     * @param createDate the value for bs_orders.create_date
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.state
     *
     * @return the value of bs_orders.state
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.state
     *
     * @param state the value for bs_orders.state
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.user_id
     *
     * @return the value of bs_orders.user_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.user_id
     *
     * @param userId the value for bs_orders.user_id
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.total_count
     *
     * @return the value of bs_orders.total_count
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.total_count
     *
     * @param totalCount the value for bs_orders.total_count
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_orders.total_amount
     *
     * @return the value of bs_orders.total_amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_orders.total_amount
     *
     * @param totalAmount the value for bs_orders.total_amount
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
}