package com.xueyuan.mapper;

import java.util.List;

import com.xueyuan.beans.Book;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_books
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_books
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_books
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_books
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_books
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int updateByPrimaryKey(Book record);
}