package com.xueyuan.mapper;

import java.util.List;

import com.xueyuan.beans.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_orders
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_orders
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_orders
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_orders
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_orders
     *
     * @mbggenerated Sat Jun 22 09:58:08 CST 2019
     */
    int updateByPrimaryKey(Order record);
}